### ISSUE TITLE
Cannot open caffemodel file. Please help!

### ISSUE THREAD

**Issue by nhoxanboc** [alexgkendall/SegNet-Tutorial#60]
Hi there, sorry for my bad English. I have done everything to build caffe-segnet in your tutorial with openblas and cpu only config on my mac, also pycaffe. When I edit webcam_demo.py file, I set 

caffe_root = '/Users/<name>/caffe-segnet'

then in terminal:

cd SegNet-Tutorial
export PYTHONPATH=/Users/<name>/caffe-segnet/python:$PYTHONPATH
python Scripts/webcam_demo.py --model Example_Models/segnet_model_driving_webdemo.prototxt --weights /Example_Models/segnet_weights_driving_webdemo.caffemodel --colours /Scripts/camvid12.png

and the error was:

Traceback (most recent call last):
  File "Scripts/webcam_demo.py", line 27, in <module>
    caffe.TEST)
RuntimeError: Could not open file /Example_Models/segnet_weights_driving_webdemo.caffemodel

Please help me in detail, I'm a beginner :)

**Comment by WeiyiLi** [comment]
Try to remove "/" before Example_Models

**Comment by nhoxanboc** [comment]
thank you very much. It solved my problem :D

**Comment by nhoxanboc** [comment]
excuse me, have you done it on your computer? it running slowly on mine, I must wait for over 15s for a frame to be processed. Is there any way to improve it?

**Comment by BlueCrow1991** [comment]
You need a GPU.

**Comment by nurhadiyatna** [comment]
Hi, I am a newbie with caffe and Segnet, I try to use webcam_Demo, however I use server to run the code, so I have no interface and webcam. So, i change to video as an input. Unfortunately I got error: 

Traceback (most recent call last):
  File "Scripts/webcam_demo.py", line 34, in <module>
    label_colours = cv2.imread(args.colours).astype(np.uint8)
AttributeError: 'NoneType' object has no attribute 'astype'

can someone help me please? 

I only change the input and output: 

`import numpy as np
import matplotlib.pyplot as plt
import os.path
import scipy
import argparse
import math
import cv2
import sys
import time


sys.path.append('/usr/local/lib/python2.7/site-packages')
# Make sure that caffe is on the python path:
caffe_root = '/home/adi005/ImageSegmentation/caffe-segnet/'
sys.path.insert(0, caffe_root + 'python')
import caffe

# Import arguments
parser = argparse.ArgumentParser()
parser.add_argument('--model', type=str, required=True)
parser.add_argument('--weights', type=str, required=True)
parser.add_argument('--colours', type=str, required=True)
args = parser.parse_args()

net = caffe.Net(args.model,
                args.weights,
                caffe.TEST)

caffe.set_mode_gpu()

input_shape = net.blobs['data'].data.shape
output_shape = net.blobs['argmax'].data.shape

label_colours = cv2.imread(args.colours).astype(np.uint8)

#cv2.namedWindow("Input")
#cv2.namedWindow("SegNet")

#cap = cv2.VideoCapture(0) # Change this to your webcam ID, or file name for your video file
cap = cv2.VideoCapture('croatia.avi')
rval = True
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi',fourcc, 20.0, (1280,720))
while rval:
	start = time.time()
	rval, frame = cap.read()

        if rval == False:
            break

	end = time.time()
	print '%30s' % 'Grabbed camera frame in ', str((end - start)*1000), 'ms'

	start = time.time()
	frame = cv2.resize(frame, (input_shape[3],input_shape[2]))
	input_image = frame.transpose((2,0,1))
	#input_image = input_image[(2,1,0),:,:] # May be required, if you do not open your data with opencv
	input_image = np.asarray([input_image])
	end = time.time()
	print '%30s' % 'Resized image in ', str((end - start)*1000), 'ms'

	start = time.time()
	out = net.forward_all(data=input_image)
	end = time.time()
	print '%30s' % 'Executed SegNet in ', str((end - start)*1000), 'ms'

	start = time.time()
	segmentation_ind = np.squeeze(net.blobs['argmax'].data)
	segmentation_ind_3ch = np.resize(segmentation_ind,(3,input_shape[2],input_shape[3]))
	segmentation_ind_3ch = segmentation_ind_3ch.transpose(1,2,0).astype(np.uint8)
	segmentation_rgb = np.zeros(segmentation_ind_3ch.shape, dtype=np.uint8)

	cv2.LUT(segmentation_ind_3ch,label_colours,segmentation_rgb)
	segmentation_rgb = segmentation_rgb.astype(float)/255

	end = time.time()
	print '%30s' % 'Processed results in ', str((end - start)*1000), 'ms\n'

#	cv2.imshow("Input", frame)
#	cv2.imshow("SegNet", segmentation_rgb)
	out.write(segmentation_rgb)
	key = cv2.waitKey(1)
	if key == 27: # exit on ESC
	    break
print 'Done'
cap.release()
#cv2.destroyAllWindows()
`
