### ISSUE TITLE
File "Scripts/test_segmentation_camvid.py", line 35, in <module>     label = net.blobs['label'].data KeyError: 'label'

### ISSUE THREAD

**Issue by yonglinZ** [alexgkendall/SegNet-Tutorial#82]
I0226 17:20:08.784281 16551 net.cpp:194] relu1_2 does not need backward computation.
I0226 17:20:08.784282 16551 net.cpp:194] conv1_2_bn does not need backward computation.
I0226 17:20:08.784284 16551 net.cpp:194] conv1_2 does not need backward computation.
I0226 17:20:08.784306 16551 net.cpp:194] relu1_1 does not need backward computation.
I0226 17:20:08.784307 16551 net.cpp:194] conv1_1_bn does not need backward computation.
I0226 17:20:08.784309 16551 net.cpp:194] conv1_1 does not need backward computation.
I0226 17:20:08.784312 16551 net.cpp:235] This network produces output argmax
I0226 17:20:08.784343 16551 net.cpp:482] Collecting Learning Rate and Weight Decay.
I0226 17:20:08.784406 16551 net.cpp:247] Network initialization done.
I0226 17:20:08.784409 16551 net.cpp:248] Memory required for data: 1065139200
Traceback (most recent call last):
  File "Scripts/test_segmentation_camvid.py", line 35, in <module>
    label = net.blobs['label'].data
KeyError: 'label'

In " test_segmentation_camvid.py" , I only modified caffe.set_mode_cpu() and the caffe_root. Please help me solve this problem.  THX.

**Comment by yonglinZ** [comment]
I have tried all of the caffemodels from SegNet Model Zoo, but still the same problem KeyError: 'label'. Anyone can help? 
Here is the cammond:
python Scripts/test_segmentation_camvid.py --model Example_Models/segnet_model_driving_webdemo.prototxt --weights Example_Models/segnet_basic_camvid.caffemodel --iter 233

**Comment by jjdblast** [comment]
I got this issue too

**Comment by yonglinZ** [comment]
Maybe, I think the caffemodel have some problem. I am trying to retrain the caffemodel according to the tutorial.

**Comment by jjdblast** [comment]
@yonglinZ Cool then, how long it'll take using caffe to train? I train a basci version of segnet using tensorlfow on K80, which tooks me about 8 hours, but it can't performance as well as the web demo.

**Comment by smohiudd** [comment]
I'm running into the same problem. Has anyone been able to figure this out?

**Comment by labibi** [comment]
@alexgkendall the same problem

**Comment by labibi** [comment]
@smohiudd @yonglinZ did you solve it?
